/lslidar_driver_node:
  ros__parameters: 
    frame_id: laser                                         #激光坐标
    group_ip: 224.1.1.2
    add_multicast: false 
    device_ip: 192.168.1.200                                #雷达目的ip
    device_ip_difop: 192.168.1.102                          #雷达源IP
    msop_port: 2368                                         #Radar target port number
    difop_port: 2369                                        #雷达源端口号
    lidar_name: M10                                         #Radar Selection:M10 M10_P M10_PLUS M10_GPS N10
    ceil_increase: -1                                        #Lsm10*时改值应设置为-1
    angle_disable_min: 160                                  #Single-angle cropping start value
    angle_disable_max: 200                                  #Single-angle cropping end value
    truncated_mode_: 0                                      #多角度裁剪开关：值为0时表示不使用多角度裁剪，默认为0
                                                            #值为1表示使用多角度裁剪，同时angle_disable_min与angle_disable_max设为 0，角度值在/lslidar_driver.cc中修改
    min_range: 0.0                                          #Minimum radar receiving distance
    max_range: 1.0                                        #Maximum radar receiving range
    use_gps_ts: false                                       #雷达是否使用GPS授时
    scan_topic: /scan                                       #设置激光数据topic名称
    interface_selection: net                             #接口选择:net 为网口,serial 为串口。
    serial_port_: /dev/wheeltec_lidar                              #串口连接时的串口号
#    pcap: /home/ls/work/2211/M10_P_gps.pcap                 #雷达是否使用pcap包读取功能
